// --- Stripe Payment Integration Demo (Client-Side) --- //

// 1. Initialize Stripe.js
// Replace 'YOUR_STRIPE_PUBLISHABLE_KEY' with your actual Stripe Publishable Key.
// You can find this in your Stripe Dashboard (Developers -> API keys).
// This key is safe to expose in client-side code.
// For demonstration, a common dummy test key is used, which will not process real payments.
const stripe = Stripe('pk_test_TYooMQauvdEDq54NiTphI7jx'); 

// 2. Get DOM elements
const checkoutButton = document.getElementById('checkout-button');
const paymentStatus = document.getElementById('payment-status');

// 3. Add event listener to the Buy button
checkoutButton.addEventListener('click', async () => {
    // Disable the button and show a loading message to prevent multiple clicks
    checkoutButton.disabled = true;
    paymentStatus.textContent = 'Initiating payment...';
    paymentStatus.className = 'status-message'; // Reset class for status messages

    console.log('Attempting to initiate Stripe Checkout...');

    // --- IMPORTANT NOTE FOR THIS DEMO ---
    // The `sessionId` required by `stripe.redirectToCheckout` MUST be generated by your server.
    // A server-side endpoint would securely call Stripe's API (using your SECRET_KEY) to create
    // a Checkout Session and then return the `session.id` to the client.
    // Since this project is strictly client-side, we cannot make a real server call.
    // Therefore, we use a placeholder `sessionId`. This will NOT lead to a real Stripe Checkout page,
    // but it demonstrates the client-side API call and the necessary error handling.

    // Example server-side (Node.js) code to create a Checkout Session:
    /*
    // In your server-side file (e.g., server.js):
    const stripe = require('stripe')('sk_test_YOUR_SECRET_KEY'); // Use your secret key here
    app.post('/create-checkout-session', async (req, res) => {
        const session = await stripe.checkout.sessions.create({
            line_items: [
                {
                    price_data: {
                        currency: 'usd',
                        product_data: {
                            name: 'Premium Membership',
                        },
                        unit_amount: 999, // $9.99
                    },
                    quantity: 1,
                },
            ],
            mode: 'payment', // or 'subscription' if setting up recurring payments
            success_url: 'https://example.com/success?session_id={CHECKOUT_SESSION_ID}',
            cancel_url: 'https://example.com/cancel',
        });
        res.json({ sessionId: session.id });
    });
    */

    // Simulate the server response with a dummy session ID.
    // In a real app, you'd fetch this from your server: 
    // const response = await fetch('/create-checkout-session', { method: 'POST' });
    // const data = await response.json();
    // const sessionId = data.sessionId;
    const dummySessionId = 'cs_test_dummy_id_12345'; // This ID is invalid and will not work with Stripe

    try {
        // Attempt to redirect to Stripe Checkout using the (dummy) session ID.
        // If the sessionId were valid and came from a server, this would redirect the user.
        const { error } = await stripe.redirectToCheckout({
            sessionId: dummySessionId,
        });

        // This block is typically reached only if there's an immediate client-side error
        // (e.g., Stripe.js not loaded, malformed sessionId, or internal client-side issues)
        // before the redirect could even happen.
        if (error) {
            console.error('Stripe Checkout Error:', error.message);
            paymentStatus.textContent = `Error: ${error.message}. A valid server-generated session ID is required for a real checkout.`;
            paymentStatus.classList.add('error');
        } else {
            // This path is rarely hit for a successful redirect as the page changes immediately.
            // If it is, it might indicate a silent redirect failure or an unexpected browser behavior.
            paymentStatus.textContent = 'Redirect failed or did not occur. Check console for details.';
            paymentStatus.classList.add('error');
        }
    } catch (e) {
        // Catch any network errors or unexpected exceptions during the Stripe.js call
        console.error('Unexpected error during Stripe redirect attempt:', e);
        paymentStatus.textContent = `An unexpected error occurred: ${e.message}. (Requires server-side session creation)`;
        paymentStatus.classList.add('error');
    }

    // Re-enable the button after the attempt (or if an error occurred before redirect)
    checkoutButton.disabled = false;

    // --- Key Concepts Not Fully Demonstrable Client-Side ---

    // 1. Webhooks:
    // Webhooks are crucial for securely handling post-payment events. After a customer completes
    // a payment via Stripe Checkout (or other Stripe events occur), Stripe sends an HTTP POST request
    // to a specified URL on your server. Your server listens for these events (e.g., 'checkout.session.completed',
    // 'payment_intent.succeeded') to update your database, fulfill orders, send confirmation emails, etc.
    // This process is entirely server-side and cannot be implemented in client-side JavaScript.
    // Example webhook listener (Node.js):
    /*
    // In your server-side file (e.g., server.js):
    app.post('/webhook', express.raw({type: 'application/json'}), (request, response) => {
        const signature = request.headers['stripe-signature'];
        let event;
        try {
            event = stripe.webhooks.constructEvent(request.body, signature, process.env.STRIPE_WEBHOOK_SECRET);
        } catch (err) {
            console.error(`Webhook Error: ${err.message}`);
            return response.status(400).send(`Webhook Error: ${err.message}`);
        }
        
        // Handle the event
        switch (event.type) {
            case 'checkout.session.completed':
                const session = event.data.object;
                console.log('Checkout session completed:', session.id);
                // Fulfill the purchase, grant access, update user status, etc.
                break;
            // Add handlers for other relevant event types like 'payment_intent.succeeded', 'invoice.paid', etc.
            default:
                console.log(`Unhandled event type ${event.type}`);
        }
        response.status(200).end();
    });
    */

    // 2. Payment Intents:
    // Payment Intents are a more granular and flexible API for managing the lifecycle of a payment.
    // They are ideal when you need to build a custom payment UI (e.g., collecting card details directly
    // on your site using Stripe Elements) or handle complex scenarios like saving cards for future use,
    // supporting various payment methods, or optimizing for specific user flows.
    // The flow typically involves:
    // a. Server: Create a Payment Intent, passing the amount and currency. Stripe returns a `client_secret`.
    // b. Client: Use `stripe.elements()` to create UI components (like card input fields) and then
    //    call `stripe.confirmCardPayment(client_secret, { payment_method: { card: cardElement } })`
    //    with the `client_secret` received from your server and the user's payment details.
    // This also heavily relies on a server-side component to create the Payment Intent and manage its state.
});
