// Get references to the HTML elements (assuming these IDs exist in your HTML)
const localVideo = document.getElementById('localVideo');
const remoteVideo = document.getElementById('remoteVideo');
const startButton = document.getElementById('startButton');
const callButton = document.getElementById('callButton');
const hangupButton = document.getElementById('hangupButton');

// Global variables to hold the streams and peer connections
let localStream;
let remoteStream;
let peerConnection1; // Represents the local peer (caller)
let peerConnection2; // Represents the remote peer (callee)

// Configuration for ICE servers (using Google's public STUN server)
const iceServers = {
    iceServers: [
        { urls: 'stun:stun.l.google.com:19302' },
        { urls: 'stun:stun1.l.google.com:19302' },
    ]
};

// Add event listeners to the buttons
startButton.onclick = startScreenShare;
callButton.onclick = establishPeerConnection;
hangupButton.onclick = hangupCall;

// Initially disable call and hangup buttons
callButton.disabled = true;
hangupButton.disabled = true;

/**
 * Starts capturing the user's screen and optionally audio.
 */
async function startScreenShare() {
    startButton.disabled = true;
    try {
        // Get display media (screen capture with optional audio)
        // audio: true allows sharing system audio if the browser/OS supports it
        localStream = await navigator.mediaDevices.getDisplayMedia({ video: true, audio: true });
        localVideo.srcObject = localStream;
        callButton.disabled = false; // Enable call button once screen is shared

        // Add a listener for when the local screen share stops (e.g., user clicks "Stop Sharing" in browser UI)
        localStream.getVideoTracks()[0].onended = () => {
            console.log('Local screen share ended by user.');
            hangupCall();
        };

    } catch (e) {
        console.error('Error starting screen share:', e);
        startButton.disabled = false; // Re-enable start button on error
        alert('Failed to start screen share. Please ensure permissions are granted.');
    }
}

/**
 * Establishes the WebRTC peer connection between two simulated peers.
 * In a real application, signaling (offer/answer/ICE candidates) would happen
 * over a WebSocket or similar server. Here, we simulate it directly.
 */
async function establishPeerConnection() {
    callButton.disabled = true;
    hangupButton.disabled = false;

    // Create RTCPeerConnection instances for two "peers"
    peerConnection1 = new RTCPeerConnection(iceServers);
    peerConnection2 = new RTCPeerConnection(iceServers);

    // --- Peer 1 (Local) Setup ---
    // Handler for ICE candidates generated by Peer 1
    peerConnection1.onicecandidate = async (event) => {
        if (event.candidate) {
            console.log('Peer 1 ICE candidate:', event.candidate);
            // Simulate sending candidate to Peer 2
            await peerConnection2.addIceCandidate(event.candidate);
        }
    };

    // Add local stream tracks to Peer 1
    localStream.getTracks().forEach(track => peerConnection1.addTrack(track, localStream));

    // --- Peer 2 (Remote) Setup ---
    // Handler for ICE candidates generated by Peer 2
    peerConnection2.onicecandidate = async (event) => {
        if (event.candidate) {
            console.log('Peer 2 ICE candidate:', event.candidate);
            // Simulate sending candidate to Peer 1
            await peerConnection1.addIceCandidate(event.candidate);
        }
    };

    // Handler for when Peer 2 receives remote tracks
    peerConnection2.ontrack = (event) => {
        console.log('Peer 2 received remote track:', event.track);
        if (remoteVideo.srcObject !== event.streams[0]) {
            remoteVideo.srcObject = event.streams[0];
            remoteStream = event.streams[0];
            console.log('Remote stream received and attached to remoteVideo.');
        }
    };

    // --- Signaling Process (Simulated) ---
    try {
        // 1. Peer 1 creates an offer (SDP)
        const offer = await peerConnection1.createOffer();
        await peerConnection1.setLocalDescription(offer);
        console.log('Peer 1 set local description (offer):', offer);

        // 2. Peer 2 receives the offer and sets it as its remote description
        await peerConnection2.setRemoteDescription(offer);
        console.log('Peer 2 set remote description (offer).');

        // 3. Peer 2 creates an answer (SDP)
        const answer = await peerConnection2.createAnswer();
        await peerConnection2.setLocalDescription(answer);
        console.log('Peer 2 set local description (answer):', answer);

        // 4. Peer 1 receives the answer and sets it as its remote description
        await peerConnection1.setRemoteDescription(answer);
        console.log('Peer 1 set remote description (answer).');

        console.log('WebRTC peer connection established!');

    } catch (e) {
        console.error('Error establishing peer connection:', e);
        alert('Failed to establish peer connection. See console for details.');
        hangupCall(); // Clean up on error
    }
}

/**
 * Hangs up the call and cleans up all resources.
 */
function hangupCall() {
    console.log('Hanging up the call.');

    // Close peer connections if they exist
    if (peerConnection1) {
        peerConnection1.close();
        peerConnection1 = null;
    }
    if (peerConnection2) {
        peerConnection2.close();
        peerConnection2 = null;
    }

    // Stop local stream tracks
    if (localStream) {
        localStream.getTracks().forEach(track => track.stop());
        localStream = null;
    }

    // Clear video sources
    localVideo.srcObject = null;
    remoteVideo.srcObject = null;

    // Reset button states
    startButton.disabled = false;
    callButton.disabled = true;
    hangupButton.disabled = true;
}
